### PR TITLE
Support Laravel ^6.0

### PR DESCRIPTION
**Pull request by erikdonohoo**
This allows the library to support Laravel ^6.0. If I missed anything, or if you have any concerns, please let me know. #8

### CODE REVIEW

**Comment by erikdonohoo** [comment]
Just realized it was not going to work on older Laravel since your `Illuminate\Support\Str` didn't exist in Laravel 5.5. I instead added the new `laravel/helpers` library to your require dev so your tests still run and pass.

**Comment by johnbwoodruff** [comment]
I need this too, thanks so much for putting this together! Hope to get this in a release soon!

**Comment by Daursu** [comment]
Thanks for submitting the PR. I don't think we need the `laravel/helpers` package. `Illuminate\Support\Str` is available in 5.5 https://github.com/laravel/framework/blob/5.5/src/Illuminate/Support/Arr.php

Once you remove that, I can merge it in

**Comment by Daursu** [comment]
I've removed the dependencies on the helpers, which were used in the tests

**Comment by erikdonohoo** [comment]
Alright @Daursu I've updated as you've requested. Would you be willing to tag this as `0.6.0` after you merge this in so we can target it in our `composer.json`?

**Comment by erikdonohoo** [comment]
I see it failed your tests for php 7.1 Since Laravel ^6.0 requires php ^7.2, the `.travis.yml` might have to be configured differently to install a diff version of Laravel for the php 7.1 tests. Or if there is some more clever way to setup your `composer.json` I'm not sure.

**Comment by Daursu** [comment]
I'm removing PHP 7.1 as it's no longer supported. If you revert the travis changes you've made, then I can merge it in and tag it with a release version

**Comment by erikdonohoo** [comment]
@Daursu I can do that, My most recent change though got it working so that php 7.1 installs an older version of the illuminate dependecies, while the newer versions install the ^6.0 deps. If you still want me to undo the changes to `.travis.yml` I can though

**Comment by Daursu** [comment]
Yes, please undo as that version of PHP is no longer supported https://www.php.net/supported-versions.php

**Comment by erikdonohoo** [comment]
@Daursu Done

**Comment by Daursu** [comment]
Thanks, will merge once the tests pass

**Comment by erikdonohoo** [comment]
@Daursu Ok, I just rebased again so the MR should look clean again.

**Comment by erikdonohoo** [comment]
Thanks a ton @Daursu , I appreciate your help!

**Comment by Daursu** [comment]
No worries! Thanks for updating the code!

**Pull request merged**
